-- Execute este arquivo uma única vez no SQL Editor do Supabase.
-- Não armazena IP, nome, e-mail ou telefone do visitante anônimo.

create table if not exists public.eventos_site (
  id bigint generated by default as identity primary key,
  criado_em timestamptz not null default now(),
  evento text not null check (evento in (
    'pagina_visualizada',
    'pesquisa_realizada',
    'resultado_pesquisa_clicado',
    'produto_visualizado',
    'carrinho_adicionado',
    'whatsapp_clicado'
  )),
  pagina text,
  caminho text,
  termo_pesquisado text,
  total_resultados integer,
  codigo_produto text,
  nome_produto text,
  origem_clique text,
  cidade text,
  regiao text,
  pais text,
  dispositivo text,
  origem text
);

alter table public.eventos_site enable row level security;

-- Nenhuma regra pública: visitantes não podem ler, alterar ou apagar os dados.
revoke all on table public.eventos_site from anon, authenticated;
revoke all on sequence public.eventos_site_id_seq from anon, authenticated;

create index if not exists eventos_site_criado_em_idx
  on public.eventos_site (criado_em desc);

create index if not exists eventos_site_evento_idx
  on public.eventos_site (evento);

create or replace view public.resumo_pesquisas_site as
select
  lower(trim(termo_pesquisado)) as pesquisa,
  count(*) as quantidade,
  max(criado_em) as ultima_pesquisa
from public.eventos_site
where evento = 'pesquisa_realizada'
  and termo_pesquisado is not null
group by lower(trim(termo_pesquisado));

create or replace view public.resumo_produtos_site as
select
  codigo_produto,
  max(nome_produto) as produto,
  count(*) filter (where evento = 'produto_visualizado') as visualizacoes,
  count(*) filter (where evento = 'carrinho_adicionado') as adicoes_carrinho,
  count(*) filter (where evento = 'whatsapp_clicado') as cliques_whatsapp
from public.eventos_site
where codigo_produto is not null
group by codigo_produto;

create or replace view public.resumo_localizacoes_site as
select
  coalesce(cidade, 'Não identificada') as cidade,
  coalesce(regiao, '-') as regiao,
  coalesce(pais, '-') as pais,
  count(*) filter (where evento = 'pagina_visualizada') as acessos
from public.eventos_site
group by cidade, regiao, pais;

revoke all on public.resumo_pesquisas_site from anon, authenticated;
revoke all on public.resumo_produtos_site from anon, authenticated;
revoke all on public.resumo_localizacoes_site from anon, authenticated;

-- Consulta rápida dos últimos eventos:
-- select * from public.eventos_site order by criado_em desc limit 100;

-- Limpeza opcional dos registros com mais de 180 dias:
-- delete from public.eventos_site where criado_em < now() - interval '180 days';
